
name: Review changes on Dev (Commits/PRs)

on:
  push:
    branches: ['dev']
  pull_request:
    types:
      - opened

jobs:
  version:
    name: code-check
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: setup flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: install flutter dependencies
        run: flutter pub get

      - name: run coverage tests
        run: flutter test --coverage

      - name: push build status to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()

